### ISSUE TITLE
Dealing with packages being renamed?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistroTools#12]
In principle, packages can "rename" themselves, simply by modifying their remote `PackageInfo.g` file. We should deal with this.

The simplest (for now) would be to simply reject this in the automation. I.e. `scan_for_updates.py` could check if the name changed, and then simply abort or so (CC @james-d-mitchell). Renames then still can be done via  manual intervention (as they might right now? @alex-konovalov ???)

We could also handle it, but then we must make sure to remove the old `meta.json` file. On a technical level, this could be dealt with as if we first delete the package with the old name (which performs checks that nothing depends on the package), and then adds the new package. I've already started implementing logic for this in my GitHub Workflow code, so that I can support "manual" PRs; but to do it from the Workflow calling `scan_for_updates.py`, that workflow must be able to detect the situation -- e.g. if `scan_for_updates.py` removed the `meta.json`, that'd work

**Comment by alex-konovalov** [comment]
Yes, right now it means:
- deleting one line and adding another to https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/currentPackageInfoURLList
- cleaning up the cache in the package update system workspace
- moving away the Mercurial repository which stores package releases (as an unfortunate side effect, old name and new name releases will not be in the same repository)

**Comment by fingolfin** [comment]
OK I think I have this under control
