### ISSUE TITLE
Preserve tarball names

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistroTools#14]
Sorry @james-d-mitchell but I think we need to preserve tarball names in `scan_for_updates`: otherwise, caching will become a nightmare, if one PR replaces e.g. anupq.tar.gz with a newer version (because it updates anupq) and then (merging of) another PR again downgrades it (because it updates another package), etc.. Also, for preserving the tarballs, we ideally should preserve them with their exact original filename.

I can probably take care of it myself later, but I wanted to record this so nobody gets surprised :-)

**Comment by james-d-mitchell** [comment]
Makes sense, I will update `scan_for_updates` to not rename the distro.
