### ISSUE TITLE
Add `download-package.py`

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistroTools#17]
Purpose: when assembling the packages, or when testing a PR, I need to ensure in the GitHub workflows that the relevant archives are really there.

Input: a list of packages of meta.json files

Effect: the archives for those packages are downloaded (if not already in `_archives`) from the URLs given in the meta.json files

Of course all the required code should already be there, among @james-d-mitchell work, it's just a matter of calling it right.

**Comment by fingolfin** [comment]
Hrm, or perhaps this is *not* needed after all, as long as `assemble-distro.py` performs its own downloading, and as long as `validate-package.py` also does it???

Then again, I may need it to download dependencies of packages being updated (so that one can load the package for testing)... but that's still rather vague

**Comment by james-d-mitchell** [comment]
This is resolved in PR #21
